name 'build_cookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
version '0.1.3'

depends 'apt'
depends 'build-essential'
depends 'chefdk'
depends 'delivery-sugar'
